# Generated by Django 4.2 on 2023-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_update_note_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
